apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: team42
spec:
  type: NodePort
  ports:
  - nodePort: 30901
    port: 9090
    protocol: TCP
    targetPort: http
  selector:
    prometheus: prometheus