apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: team42
spec:
  serviceAccountName: prometheus
  podMonitorSelector:
    matchLabels:
      team: team42
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false